from __future__ import annotations

from pfi_os.backtest import BacktestConfig, BacktestEngine
from pfi_os.data import assess_bars, save_quality_report
from pfi_os.data.models import BarDataRequest
from pfi_os.data.providers import SampleDataProvider
from pfi_os.reports import export_backtest_docx
from pfi_os.strategies import MovingAverageCrossoverStrategy


def main() -> None:
    provider = SampleDataProvider(seed=7)
    request = BarDataRequest(symbol="AAPL", market="US", interval="1d", start="2020-01-01", end="2024-12-31")
    data = provider.get_bars(request)
    quality = assess_bars(data, provider=provider.name, symbol=request.symbol, market=request.market, interval=request.interval)
    quality_path = save_quality_report(quality)
    strategy = MovingAverageCrossoverStrategy(short_window=20, long_window=60)
    engine = BacktestEngine(BacktestConfig(initial_cash=100_000, commission_rate=0.001, slippage_bps=5))
    result = engine.run(data, strategy)
    result.metadata["entity"] = {
        "status": "TradableSymbol",
        "canonical_symbol": request.symbol,
        "market": request.market,
        "source": "SampleReportScript",
    }
    result.metadata["workflow"] = {
        "source_system": "SampleReportScript",
        "lineage_note": "Generated by scripts/createSampleReport.sh; no ResearchBus chat input was required.",
    }
    report_path = export_backtest_docx(result, report_name="SampleBacktestReport", data_quality_report=quality)
    print("Metrics:")
    for key, value in result.metrics.items():
        print(f"  {key}: {value}")
    print(f"DataQuality: {quality.quality_status}")
    print(f"WordReport: {report_path}")
    print(f"QualityReport: {quality_path}")


if __name__ == "__main__":
    main()
