// Generated by x2n_contracts.generate. Do not edit by hand.
export const CONTRACT_VERSION = "1.0" as const;
export type SchemaVersion = typeof CONTRACT_VERSION;
export type ISODateTime = string;
export type UUID = string;
export type Sha256 = string;
export type OpaqueRef = string;
export type ContractKey = string;

export function canonicalPayloadJson(value: unknown): string {
  if (value === null || typeof value === "boolean" || typeof value === "string") {
    const encoded = JSON.stringify(value);
    if (encoded === undefined) throw new TypeError("payload value is not JSON serializable");
    return encoded;
  }
  if (typeof value === "number") {
    if (!Number.isSafeInteger(value)) throw new TypeError("payload numbers must be safe integers");
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalPayloadJson(item)).join(",")}]`;
  }
  if (typeof value === "object") {
    const record = value as Record<string, unknown>;
    const pairs = Object.keys(record)
      .sort()
      .map((key) => `${JSON.stringify(key)}:${canonicalPayloadJson(record[key])}`);
    return `{${pairs.join(",")}}`;
  }
  throw new TypeError("payload contains a non-JSON value");
}

export async function computePayloadHash(payload: unknown): Promise<Sha256> {
  const bytes = new TextEncoder().encode(canonicalPayloadJson(payload));
  const digest = await crypto.subtle.digest("SHA-256", bytes);
  return Array.from(new Uint8Array(digest), (value) => value.toString(16).padStart(2, "0")).join("");
}

export const PLATFORMS = ["xiaohongshu", "douyin", "bilibili", "kuaishou", "weibo", "taobao"] as const;
export type Platform = (typeof PLATFORMS)[number];
export const NATIVE_ACTIONS = ["capture_current", "start_sync", "get_job", "cancel_job", "retry_job", "get_capabilities", "health"] as const;
export type NativeAction = (typeof NATIVE_ACTIONS)[number];
export const ERROR_CLASSES = ["user_action_required", "platform_changed", "rate_limited", "network", "dependency_missing", "provider", "invalid_input", "security_blocked", "storage", "data_integrity", "policy", "unknown"] as const;
export type ErrorClass = (typeof ERROR_CLASSES)[number];
export const ERROR_CODES = ["X2N_INVALID_SCHEMA_VERSION", "X2N_UNKNOWN_FIELD", "X2N_INVALID_INPUT", "X2N_NATIVE_ORIGIN_REJECTED", "X2N_NATIVE_MESSAGE_TOO_LARGE", "X2N_NATIVE_ACTION_UNKNOWN", "X2N_NATIVE_DUPLICATE_REQUEST", "X2N_CANONICAL_KEY_INVALID", "X2N_RELATION_KEY_INVALID", "X2N_ARTIFACT_VERSION_CONFLICT", "X2N_PROVENANCE_INCOMPLETE", "X2N_CDN_PERSISTENCE_BLOCKED", "X2N_URL_REJECTED", "X2N_SECURITY_INJECTION_BLOCKED", "X2N_ADAPTER_AUTH_EXPIRED", "X2N_PLATFORM_CHANGED", "X2N_RATE_LIMITED", "X2N_NETWORK_FAILED", "X2N_DEPENDENCY_MISSING", "X2N_PROVIDER_FAILED", "X2N_STORAGE_FAILED", "X2N_DATA_INTEGRITY_FAILED", "X2N_POLICY_BLOCKED", "X2N_UNKNOWN_FAILURE"] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
export const DATA_EFFECTS = ["none", "canonical_unchanged", "derived_output_missing", "unknown_fail_closed"] as const;
export type DataEffect = (typeof DATA_EFFECTS)[number];
export const NEXT_ACTIONS = ["correct_input", "review_security_event", "use_existing_job", "restore_backup", "review_policy", "open_login_profile", "inspect_platform_fixture", "wait_and_retry", "retry", "install_dependency", "inspect_provider", "free_disk_space", "inspect_diagnostics"] as const;
export type NextAction = (typeof NEXT_ACTIONS)[number];

export type ContentType = "text" | "image_gallery" | "video" | "mixed" | "unknown";
export type ContentStatus = "active" | "unavailable" | "unknown" | "deleted_by_user";
export type RelationType = "liked" | "favorited" | "saved_current";
export type RelationStatus = "active" | "unknown" | "tombstone_candidate" | "removed";
export type ConfirmationSource = "scan" | "owner";
export type ArtifactType = "transcript" | "ocr" | "vision" | "fusion_summary" | "search_text";
export type SinkKind = "markdown" | "notion";
export type DuplicateDisposition = "new_request" | "return_existing_job" | "reject_conflict";

export interface ErrorContract {
  readonly schema_version: SchemaVersion;
  readonly code: ErrorCode;
  readonly class: ErrorClass;
  readonly retryable: boolean;
  readonly safe_message: string;
  readonly internal_ref: OpaqueRef;
  readonly data_effect: DataEffect;
  readonly next_action: NextAction;
}

export interface PageContext {
  readonly content_id: string;
  readonly title?: string | null;
  readonly content_type: ContentType;
}

export interface CaptureCurrentPayload {
  readonly platform: Platform;
  readonly page_url: string;
  readonly page_context: PageContext;
  readonly relation: "saved_current";
  readonly category_id?: UUID | null;
  readonly user_gesture: true;
  readonly auto_scroll: false;
  readonly change_account_state: false;
}

export interface StartSyncPayload {
  readonly platform: Platform;
  readonly relation: "liked" | "favorited";
  readonly source_collection_id?: string | null;
  readonly max_items: number;
  readonly user_gesture: true;
  readonly bounded_batch: true;
  readonly auto_scroll: false;
  readonly change_account_state: false;
}

export interface JobPayload {
  readonly job_id: UUID;
}

export type EmptyPayload = Record<string, never>;

export interface NativeRequestEnvelope<A extends NativeAction, P> {
  readonly schema_version: SchemaVersion;
  readonly request_id: UUID;
  readonly action: A;
  readonly sent_at: ISODateTime;
  readonly payload: P;
  readonly payload_hash: Sha256;
}

export type NativeMessageRequest =
  | NativeRequestEnvelope<"capture_current", CaptureCurrentPayload>
  | NativeRequestEnvelope<"start_sync", StartSyncPayload>
  | NativeRequestEnvelope<"get_job", JobPayload>
  | NativeRequestEnvelope<"cancel_job", JobPayload>
  | NativeRequestEnvelope<"retry_job", JobPayload>
  | NativeRequestEnvelope<"get_capabilities", EmptyPayload>
  | NativeRequestEnvelope<"health", EmptyPayload>;

export type NativeResponseStatus = "queued" | "running" | "completed" | "rejected";

export interface NativeMessageResponse {
  readonly schema_version: SchemaVersion;
  readonly request_id: UUID;
  readonly accepted: boolean;
  readonly job_id?: UUID | null;
  readonly status: NativeResponseStatus;
  readonly error?: ErrorContract | null;
}

export interface NativeHostPolicy {
  readonly schema_version: SchemaVersion;
  readonly policy_id: "NATIVE_HOST.X2N.001";
  readonly allowed_origins: readonly string[];
  readonly allowed_actions: readonly NativeAction[];
  readonly max_message_bytes: number;
  readonly request_id_window_seconds: 86400;
  readonly duplicate_policy: "return_existing_job_only";
  readonly unknown_fields: "reject";
  readonly unknown_versions: "reject";
  readonly arbitrary_shell: "reject";
  readonly arbitrary_local_path: "reject";
  readonly arbitrary_url: "reject";
}

export interface CanonicalContent {
  readonly schema_version: SchemaVersion;
  readonly content_key: ContractKey;
  readonly platform: Platform;
  readonly platform_content_id: string;
  readonly canonical_source_url: string;
  readonly content_type: ContentType;
  readonly title?: string | null;
  readonly description?: string | null;
  readonly author_name?: string | null;
  readonly author_platform_id?: string | null;
  readonly published_at?: ISODateTime | null;
  readonly content_hash: Sha256;
  readonly first_observed_at: ISODateTime;
  readonly last_observed_at: ISODateTime;
  readonly record_version: number;
  readonly status: ContentStatus;
}

export interface UserRelation {
  readonly schema_version: SchemaVersion;
  readonly relation_key: ContractKey;
  readonly account_ref_hash: Sha256;
  readonly content_key: ContractKey;
  readonly relation_type: RelationType;
  readonly source_collection_id?: string | null;
  readonly source_collection_name_private?: string | null;
  readonly first_seen_at: ISODateTime;
  readonly last_seen_at: ISODateTime;
  readonly status: RelationStatus;
  readonly confirmed_by: ConfirmationSource;
  readonly scan_receipt_id: OpaqueRef;
}

export type SourceMethod = "current_page" | "selected_collection" | "adapter_supplement";
export type CanonicalField = "platform_content_id" | "canonical_source_url" | "content_type" | "title" | "description" | "author_name" | "author_platform_id" | "published_at";
export type FieldSource = "dom" | "adapter" | "owner" | "derived";
export type FieldStatus = "present" | "unavailable" | "unknown";

export interface FieldProvenance {
  readonly field: CanonicalField;
  readonly source: FieldSource;
  readonly status: FieldStatus;
  readonly confidence?: number | null;
}

export interface SourceObservation {
  readonly schema_version: SchemaVersion;
  readonly observation_id: OpaqueRef;
  readonly content_key: ContractKey;
  readonly adapter_name: string;
  readonly adapter_version: string;
  readonly source_method: SourceMethod;
  readonly observed_at: ISODateTime;
  readonly raw_text_hash: Sha256;
  readonly normalized_fields: readonly CanonicalField[];
  readonly field_provenance: readonly FieldProvenance[];
  readonly completeness: number;
  readonly warning_codes?: readonly ErrorCode[];
  readonly ephemeral_media_ref_ids?: readonly OpaqueRef[];
  readonly run_id: OpaqueRef;
}

export type QualityGrade = "high" | "medium" | "low" | "unknown";
export interface ArtifactQuality {
  readonly grade: QualityGrade;
  readonly metric_name?: string | null;
  readonly metric_value?: number | null;
}

export interface Artifact {
  readonly schema_version: SchemaVersion;
  readonly artifact_id: OpaqueRef;
  readonly artifact_key: ContractKey;
  readonly content_key: ContractKey;
  readonly artifact_type: ArtifactType;
  readonly input_hash: Sha256;
  readonly processor: string;
  readonly processor_version: string;
  readonly model_provider?: string | null;
  readonly model_name?: string | null;
  readonly model_snapshot?: string | null;
  readonly prompt_version?: string | null;
  readonly language?: string | null;
  readonly quality: ArtifactQuality;
  readonly private_payload_present: boolean;
  readonly private_payload_ref?: OpaqueRef | null;
  readonly private_payload_hash?: Sha256 | null;
  readonly append_only: true;
  readonly artifact_sequence: number;
  readonly created_at: ISODateTime;
  readonly supersedes_artifact_id?: OpaqueRef | null;
}

export interface TaxonomyCategory {
  readonly schema_version: SchemaVersion;
  readonly category_id: UUID;
  readonly name: string;
  readonly slug: string;
  readonly description: string;
  readonly aliases?: readonly string[];
  readonly positive_examples?: readonly string[];
  readonly negative_examples?: readonly string[];
  readonly priority: number;
  readonly enabled: boolean;
  readonly version: number;
  readonly level: 1;
  readonly created_by: "owner";
}

export type DecisionMode = "rule" | "model" | "hybrid" | "human";
export type ReviewStatus = "auto_accepted" | "suggested" | "owner_confirmed" | "owner_corrected";
export interface ClassificationCandidate {
  readonly category_id: UUID;
  readonly calibrated_score: number;
}

export interface Classification {
  readonly schema_version: SchemaVersion;
  readonly classification_id: OpaqueRef;
  readonly content_key: ContractKey;
  readonly taxonomy_version: number;
  readonly primary_category_id: UUID;
  readonly tags?: readonly string[];
  readonly candidate_ranking?: readonly ClassificationCandidate[];
  readonly decision_mode: DecisionMode;
  readonly confidence_raw?: number | null;
  readonly calibration_bucket?: string | null;
  readonly evidence_artifact_ids: readonly OpaqueRef[];
  readonly explanation_private_ref?: OpaqueRef | null;
  readonly review_status: ReviewStatus;
  readonly created_at: ISODateTime;
  readonly supersedes_classification_id?: OpaqueRef | null;
}

export type SinkReceiptStatus = "delivered" | "verified" | "failed";
export interface SinkReceipt {
  readonly schema_version: SchemaVersion;
  readonly receipt_id: OpaqueRef;
  readonly sink_key: ContractKey;
  readonly sink: SinkKind;
  readonly content_key: ContractKey;
  readonly sink_schema_version: string;
  readonly desired_projection_hash: Sha256;
  readonly output_hash: Sha256;
  readonly sink_object_ref: OpaqueRef;
  readonly external_ref_hash?: Sha256 | null;
  readonly status: SinkReceiptStatus;
  readonly delivered_at: ISODateTime;
  readonly run_id: OpaqueRef;
}

export type HealthComponentName = "extension" | "native_host" | "companion" | "canonical_db" | "ffmpeg" | "provider" | "notion" | "adapter";
export type HealthState = "healthy" | "degraded" | "unavailable" | "failed";
export interface HealthComponent {
  readonly component: HealthComponentName;
  readonly state: HealthState;
  readonly observed_at: ISODateTime;
  readonly error?: ErrorContract | null;
}
export interface HealthReport {
  readonly schema_version: SchemaVersion;
  readonly report_id: OpaqueRef;
  readonly observed_at: ISODateTime;
  readonly overall: HealthState;
  readonly components: readonly HealthComponent[];
}

export type ProvenanceNodeKind = "canonical" | "source_observation" | "adapter" | "artifact" | "classification" | "run" | "renderer" | "sink_receipt";
export interface ProvenanceNode {
  readonly node_id: string;
  readonly kind: ProvenanceNodeKind;
  readonly reference: string;
  readonly version: string;
  readonly evidence_hash: Sha256;
}
export interface ProvenanceEdge {
  readonly from_node_id: string;
  readonly to_node_id: string;
  readonly relation: "traces_to";
}
export interface ProvenanceChain {
  readonly schema_version: SchemaVersion;
  readonly chain_id: OpaqueRef;
  readonly content_key: ContractKey;
  readonly output_kind: SinkKind;
  readonly output_node_id: string;
  readonly nodes: readonly ProvenanceNode[];
  readonly edges: readonly ProvenanceEdge[];
  readonly completeness_percent: 100;
}

export interface CompatibilityPolicy {
  readonly schema_version: SchemaVersion;
  readonly contract_version: SchemaVersion;
  readonly accepted_read_versions: readonly SchemaVersion[];
  readonly compatibility_mode: "exact_match_fail_closed";
  readonly unknown_fields: "reject";
  readonly unknown_versions: "reject";
  readonly destructive_migration: "forbidden_without_versioned_migration";
}
