"""Public API for the x2n 1.0 contract package."""

from .base import CONTRACT_VERSION, canonical_json_sha256
from .errors import ERROR_SPECS, DataEffect, ErrorClass, ErrorCode, NextAction
from .models import (
    Artifact,
    CanonicalContent,
    Classification,
    CompatibilityPolicy,
    ContractViolation,
    DuplicateDisposition,
    ErrorContract,
    HealthReport,
    NativeHostPolicy,
    NativeMessageRequest,
    NativeMessageResponse,
    Platform,
    ProvenanceChain,
    SinkReceipt,
    SourceObservation,
    TaxonomyCategory,
    UserRelation,
    build_artifact_key,
    build_content_key,
    build_relation_key,
    build_sink_key,
    classify_duplicate_request,
    parse_native_message,
)

__all__ = [
    "CONTRACT_VERSION",
    "ERROR_SPECS",
    "Artifact",
    "CanonicalContent",
    "Classification",
    "CompatibilityPolicy",
    "ContractViolation",
    "DataEffect",
    "DuplicateDisposition",
    "ErrorClass",
    "ErrorCode",
    "ErrorContract",
    "HealthReport",
    "NativeHostPolicy",
    "NativeMessageRequest",
    "NativeMessageResponse",
    "NextAction",
    "Platform",
    "ProvenanceChain",
    "SinkReceipt",
    "SourceObservation",
    "TaxonomyCategory",
    "UserRelation",
    "build_artifact_key",
    "build_content_key",
    "build_relation_key",
    "build_sink_key",
    "canonical_json_sha256",
    "classify_duplicate_request",
    "parse_native_message",
]
