import { normalizeText } from "./util.js";

/** @param {import('./model.js').CanonicalSnapshot} snapshot @param {Array<{sourceId:string,path:string}>} books */
export function renderOfflineSearch(snapshot, books) {
  const pathById = new Map(books.map(book => [book.sourceId, `../${book.path}`]));
  const records = [];
  for (const book of snapshot.books) {
    for (const item of book.highlights) records.push({ book: book.metadata.title, author: book.metadata.author, chapter: item.chapterTitle, type: "划线", text: item.text, date: item.createdAtIso ?? "", path: pathById.get(book.source.bookId) });
    for (const item of book.thoughts) records.push({ book: book.metadata.title, author: book.metadata.author, chapter: item.chapterTitle, type: item.kind === "book-review" ? "书评" : "想法", text: item.content, quote: item.abstract ?? "", date: item.createdAtIso ?? "", path: pathById.get(book.source.bookId) });
  }
  records.sort((a, b) => a.book.localeCompare(b.book, "zh-CN") || String(a.chapter).localeCompare(String(b.chapter), "zh-CN") || String(a.text).localeCompare(String(b.text), "zh-CN"));
  const data = JSON.stringify(records).replace(/</g, "\\u003c").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
  return `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>微信读书笔记离线搜索</title>
<style>:root{color-scheme:light dark;font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}body{margin:0;background:#0b1324;color:#eef4ff}main{max-width:960px;margin:auto;padding:32px 18px 80px}h1{font-size:clamp(1.8rem,4vw,3rem);margin:.2em 0}.sub{color:#a9b7d0}input{box-sizing:border-box;width:100%;padding:15px 17px;border-radius:14px;border:1px solid #33415c;background:#111c31;color:inherit;font-size:1rem;margin:20px 0}#count{font-variant-numeric:tabular-nums}.card{display:block;color:inherit;text-decoration:none;border:1px solid #2d3a55;background:#101b30;border-radius:16px;padding:16px;margin:12px 0}.card:hover{border-color:#79a7ff}.meta{color:#9fb0ce;font-size:.88rem}.quote{border-left:3px solid #6788c7;padding-left:12px;color:#c7d4e9;white-space:pre-wrap}.text{white-space:pre-wrap;line-height:1.65}mark{background:#ffd86b;color:#111827;border-radius:3px;padding:0 2px}.empty{padding:36px 0;color:#9fb0ce}@media(prefers-color-scheme:light){body{background:#f6f8fc;color:#14213d}.sub,.meta,.empty{color:#5a6882}input,.card{background:#fff;border-color:#d8dfeb}.quote{color:#394761}}</style></head>
<body><main><h1>离线笔记搜索</h1><p class="sub">数据只在这个 HTML 文件里。直接双击打开即可搜索，不会向服务器发送笔记。</p><input id="q" type="search" autocomplete="off" placeholder="搜索书名、作者、章节、划线或想法…" aria-label="搜索"><p id="count"></p><section id="results"></section></main>
<script>const DATA=${data};const q=document.getElementById('q'),out=document.getElementById('results'),count=document.getElementById('count');const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function render(){const term=q.value.trim().toLocaleLowerCase('zh-CN');const rows=(term?DATA.filter(r=>[r.book,r.author,r.chapter,r.type,r.text,r.quote].join('\n').toLocaleLowerCase('zh-CN').includes(term)):DATA).slice(0,500);count.textContent=(term?'匹配 ':'共 ')+rows.length+(rows.length===500?'（仅显示前 500 条）':'')+' 条';out.innerHTML=rows.length?rows.map(r=>'<a class="card" href="'+esc(r.path)+'"><div class="meta">'+esc(r.book)+' · '+esc(r.author)+' · '+esc(r.chapter)+' · '+esc(r.type)+(r.date?' · '+esc(r.date):'')+'</div>'+(r.quote?'<p class="quote">'+esc(r.quote)+'</p>':'')+'<p class="text">'+esc(r.text)+'</p></a>').join(''):'<p class="empty">没有匹配结果。</p>'}q.addEventListener('input',render);render();</script></body></html>`;
}
