from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORTS = {
    "DEFAULT_CONSUMER_HOLDINGS_DIRS": "external_systems",
    "DEFAULT_INDUSTRY_REPORT_DIR": "external_systems",
    "DEFAULT_PFI_HOLDINGS_DIRS": "external_systems",
    "build_personal_profile": "external_systems",
    "collect_industry_reports": "external_systems",
    "external_system_status": "external_systems",
    "filter_industry_reports": "external_systems",
    "holdings_summary": "external_systems",
    "load_holding_sources_from_dirs": "external_systems",
    "load_holdings_frame": "external_systems",
    "consumer_behavior_state_frame": "consumer_behavior",
    "read_consumer_behavior_state": "consumer_behavior",
    "sync_consumer_behavior_state": "consumer_behavior",
    "HOLDINGS_BOOK_PATH": "holdings_book",
    "HOLDINGS_EXPORT_PATH": "holdings_book",
    "HOLDINGS_HISTORY_PATH": "holdings_book",
    "canonical_holdings_frame": "holdings_book",
    "default_holding_source_specs": "holdings_book",
    "export_holdings_csv": "holdings_book",
    "holdings_exposure_frame": "holdings_book",
    "holdings_quality_frame": "holdings_book",
    "holdings_sync_history_frame": "holdings_book",
    "load_candidate_holdings_frame": "holdings_book",
    "load_current_holdings": "holdings_book",
    "load_holdings_book": "holdings_book",
    "load_pending_orders_frame": "holdings_book",
    "scan_holding_sources": "holdings_book",
    "sync_holdings_book": "holdings_book",
    "upsert_manual_holding": "holdings_book",
    "ENTITY_REGISTRY_DIR": "holding_symbol_map",
    "HOLDING_SYMBOL_MAP_PATH": "holding_symbol_map",
    "EntityRecord": "holding_symbol_map",
    "HoldingSymbolProxy": "holding_symbol_map",
    "build_entity_registry": "holding_symbol_map",
    "entity_registry_frame": "holding_symbol_map",
    "holdings_symbol_proxy_frame": "holding_symbol_map",
    "resolve_holding_symbol_proxy": "holding_symbol_map",
    "write_entity_registry": "holding_symbol_map",
    "INDEPENDENT_VALIDATION_DIR": "independent_validation",
    "independent_validation_runs_frame": "independent_validation",
    "run_independent_validation": "independent_validation",
    "write_manifest": "independent_validation",
    "RESEARCH_BUS_DB_PATH": "research_bus",
    "RESEARCH_BUS_SNAPSHOT_PATH": "research_bus",
    "bus_pfi_os_results_frame": "research_bus",
    "bus_validation_task_frame": "research_bus",
    "export_research_bus_snapshot": "research_bus",
    "holding_symbol_mappings_frame": "research_bus",
    "holding_update_candidates_frame": "research_bus",
    "initialize_research_bus": "research_bus",
    "load_default_portfolio_transactions": "research_bus",
    "portfolio_transactions_frame": "research_bus",
    "push_bus_validation_tasks_to_pfi_os_queue": "research_bus",
    "research_bus_db_path": "research_bus",
    "research_bus_status_frame": "research_bus",
    "sync_all_research_bus": "research_bus",
    "sync_holding_symbol_mappings_to_bus": "research_bus",
    "sync_holdings_to_bus": "research_bus",
    "sync_industry_reports_to_bus": "research_bus",
    "sync_portfolio_transactions_to_bus": "research_bus",
    "sync_pfi_os_results_to_bus": "research_bus",
    "CHAT_DROPBOX_DIR": "research_bus_api",
    "bus_api_requests_frame": "research_bus_api",
    "bus_chat_inputs_frame": "research_bus_api",
    "bus_heartbeats_frame": "research_bus_api",
    "classify_chat_input": "research_bus_api",
    "confirm_holding_update_candidate": "research_bus_api",
    "complete_bus_request": "research_bus_api",
    "heartbeat_system": "research_bus_api",
    "pending_bus_requests_frame": "research_bus_api",
    "process_chat_dropbox": "research_bus_api",
    "process_pending_bus_requests": "research_bus_api",
    "research_bus_health_summary": "research_bus_api",
    "submit_bus_request": "research_bus_api",
    "submit_chat_input": "research_bus_api",
    "submit_webhook_payload": "research_bus_api",
    "workflow_inputs_frame": "research_bus_api",
    "AUDIT_OUTPUT_PATH": "research_bus_audit",
    "run_research_bus_interop_audit": "research_bus_audit",
    "ChildSystemDefinition": "system_orchestrator",
    "default_child_systems": "system_orchestrator",
    "orchestrate_child_system": "system_orchestrator",
    "orchestration_runs_frame": "system_orchestrator",
    "register_default_systems": "system_orchestrator",
    "sync_default_system_artifacts": "system_orchestrator",
    "system_artifacts_frame": "system_orchestrator",
    "system_registry_frame": "system_orchestrator",
    "WORKSPACE_SYSTEM_IDS": "workspace_systems",
    "WorkspaceSystemSummary": "workspace_systems",
    "compact_workspace_system_payload": "workspace_systems",
    "load_workspace_system_summaries": "workspace_systems",
    "SITE52ETF_COMPARISON_SCHEMA": "site52etf",
    "SITE52ETF_PUBLIC_SNAPSHOT_SCHEMA": "site52etf",
    "SITE52ETF_URL": "site52etf",
    "build_site52etf_hotspot_comparison": "site52etf",
    "build_site52etf_public_snapshot": "site52etf",
    "fetch_52etf_public_snapshot": "site52etf",
    "load_site52etf_public_snapshot_latest": "site52etf",
    "parse_52etf_public_page": "site52etf",
    "site52etf_comparison_rows": "site52etf",
    "site52etf_summary_rows": "site52etf",
    "write_site52etf_public_snapshot": "site52etf",
}

__all__ = sorted(_EXPORTS)


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(f"{__name__}.{_EXPORTS[name]}")
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
