'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const { UserMessageRuntime } = require('../../src/v8-prebuilt/runtime/user-message-runtime');
function message(text,id='m1'){return{from_user_id:'sender',context_token:'context',message_id:id,item_list:[{text_item:{text}}]};}
function harness({controller,commandHandler=null}={}){const staged=[];let calls=0;const runtime=new UserMessageRuntime({sharedController:controller||{async execute(input){calls+=1;assert.equal(input.userId,'u1');return{ok:true,providerCalls:1,result:{outputText:'DeepSeek 回复'}};}},userRepository:{getById:()=>({userId:'u1',role:'user',status:'active'})},replyOutbox:{stage:(row)=>staged.push(row)},encrypt:({value})=>value,routeKey:Buffer.alloc(32,5),commandHandler});return{runtime,staged,getCalls:()=>calls};}
test('active ordinary user is routed only through shared DeepSeek controller',async()=>{const h=harness();const result=await h.runtime.handle({userId:'u1',accountId:'bot',message:message('你好')});assert.equal(h.getCalls(),1);assert.equal(result.modelCalls,1);assert.equal(h.staged[0].bodyCiphertext.text,'DeepSeek 回复');});
test('capacity/global cap errors produce Chinese deterministic reply without hidden provider fallback',async()=>{const h=harness({controller:{async execute(){return{ok:false,code:'GLOBAL_DAILY_TOKEN_CAP',providerCalls:0};}}});const result=await h.runtime.handle({userId:'u1',accountId:'bot',message:message('继续','m2')});assert.equal(result.modelCalls,0);assert.match(h.staged[0].bodyCiphertext.text,/10 亿 Token/);});
test('help and AI status are deterministic and call no model',async()=>{const h=harness();let result=await h.runtime.handle({userId:'u1',accountId:'bot',message:message('帮助','m3')});assert.equal(result.modelCalls,0);assert.equal(h.getCalls(),0);assert.match(h.staged.at(-1).bodyCiphertext.text,/直接发一句话/);result=await h.runtime.handle({userId:'u1',accountId:'bot',message:message('连接AI','m4')});assert.equal(result.modelCalls,0);assert.equal(h.getCalls(),0);assert.match(h.staged.at(-1).bodyCiphertext.text,/DeepSeek V4 Pro/);});
test('portal-style command uses deterministic handler and never falls through to DeepSeek',async()=>{const h=harness({commandHandler:async({command})=>({text:`安全链接：${command}`,modelCalls:0})});const result=await h.runtime.handle({userId:'u1',accountId:'bot',message:message('导入聊天','m5')});assert.equal(result.modelCalls,0);assert.equal(h.getCalls(),0);assert.match(h.staged[0].bodyCiphertext.text,/portal.import/);});
