'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const{DatabaseSync}=require('node:sqlite');
const{SharedEntryService,normalizeEntryUrl}=require('../../src/v8-prebuilt/public-entry/shared-entry-service');
const{SqliteOwnerActivationStore}=require('../../src/v8-prebuilt/public-entry/owner-activation-store');
const{OwnerWeChatActivationService}=require('../../src/v8-prebuilt/public-entry/owner-wechat-activation-service');
const{SharedBotAccountStore}=require('../../src/v8-prebuilt/weixin/shared-bot-account-store');
const{renderQrSvg}=require('../../src/v8-prebuilt/public-entry/qr-svg');
function db(){const x=new DatabaseSync(':memory:');x.exec(fs.readFileSync(path.join(__dirname,'../../migrations/multiuser_foundation.sql.template'),'utf8'));x.exec(fs.readFileSync(path.join(__dirname,'../../migrations/public_scan_entry.sql.template'),'utf8'));x.prepare(`INSERT INTO users(user_id,role,status,created_at,updated_at) VALUES(?,?,?,?,?)`).run('owner','owner','active','x','x');return x;}
test('public shared entry is pending before owner activation and ready after activation',()=>{const x=db();const accounts=new SharedBotAccountStore({db:x,masterKey:Buffer.alloc(32,1),ownerUserId:'owner',clock:()=>1000});const entry=new SharedEntryService({entryUrlProvider:()=> 'https://weixin.qq.com/g/synthetic-entry',sharedBotState:()=>accounts.publicState(),clock:()=>1000});assert.deepEqual(entry.summary().ready,false);accounts.activate({accountId:'shared-bot',botToken:'synthetic-token',baseUrl:'https://ilink.invalid/',weixinUserId:'owner-wx'});const ready=entry.summary();assert.equal(ready.ready,true);assert.equal(ready.status,'ready');assert.match(ready.qrDataUri,/^data:image\/svg\+xml;base64,/);assert.equal(x.prepare(`SELECT COUNT(*) AS n FROM weixin_accounts`).get().n,1);assert.equal(x.prepare(`SELECT COUNT(*) AS n FROM users WHERE role='user'`).get().n,0);x.close();});
test('owner-only iLink authorization activates exactly one shared bot and creates no ordinary user',async()=>{const x=db();let now=1000;const accounts=new SharedBotAccountStore({db:x,masterKey:Buffer.alloc(32,2),ownerUserId:'owner',clock:()=>now});const store=new SqliteOwnerActivationStore(x);let polls=0;const service=new OwnerWeChatActivationService({client:{async createQr(){return{qrId:'owner-qr-1',content:'https://scan.invalid/owner'};},async pollStatus(){polls+=1;if(polls===1)return{status:'scanned'};return{status:'confirmed',accountId:'shared-bot',botToken:'synthetic-token',baseUrl:'https://ilink.invalid/',weixinUserId:'owner-wx'};}},store,sharedBotAccounts:accounts,clock:()=>now,ttlMs:5000});const created=await service.create();assert.equal(created.status,'wait');assert.match(created.qrDataUri,/^data:image\/svg\+xml;base64,/);assert.equal((await service.status(created.sessionId)).status,'scanned');assert.equal((await service.status(created.sessionId)).status,'confirmed');assert.equal(accounts.getActive().accountId,'shared-bot');assert.equal(x.prepare(`SELECT COUNT(*) AS n FROM weixin_accounts`).get().n,1);assert.equal(x.prepare(`SELECT COUNT(*) AS n FROM users WHERE role='user'`).get().n,0);assert.doesNotMatch(x.prepare(`SELECT token_ciphertext AS c FROM weixin_accounts`).get().c,/synthetic-token/);x.close();});
test('entry URL and QR renderer fail closed on dangerous input',()=>{assert.throws(()=>normalizeEntryUrl('javascript:alert(1)'),/FORBIDDEN/);assert.throws(()=>normalizeEntryUrl('https://user:pass@example.invalid/'),/CREDENTIAL/);const svg=renderQrSvg('https://weixin.qq.com/g/synthetic-entry');assert.match(svg,/<svg/);assert.doesNotMatch(svg,/script/i);});
