const app=document.querySelector('#app');
const pct=value=>Number.isFinite(Number(value))?`${(Number(value)*100).toFixed(1)}%`:'—';
const time=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false}):'—';
function node(tag,text,attrs={}){const item=document.createElement(tag);if(text!==undefined)item.textContent=text;for(const [key,value] of Object.entries(attrs)){item.setAttribute(key,value)}return item}
function panel(title,description){const section=node('section',undefined,{class:'panel section-block'});const header=node('header');header.append(node('div'));header.firstChild.append(node('h2',title));if(description)header.firstChild.append(node('p',description));section.append(header);return section}
function table(headers,rows){const wrap=node('div',undefined,{class:'table-wrap',tabindex:'0'});const tableElement=node('table');const head=node('thead');const headRow=node('tr');headers.forEach(value=>headRow.append(node('th',value)));head.append(headRow);tableElement.append(head);const body=node('tbody');rows.forEach(row=>{const tr=node('tr');row.forEach(value=>tr.append(node('td',String(value))));body.append(tr)});tableElement.append(body);wrap.append(tableElement);return wrap}
function renderBlocked(){app.setAttribute('aria-busy','false');app.replaceChildren();const main=node('main',undefined,{id:'main-content',class:'blocked-page',tabindex:'-1'});main.append(node('p','SYSTEM_BLOCKED',{class:'eyebrow'}));main.append(node('h1','数据链路不完整，不出结论'));app.append(main)}
function renderSources(report){const section=panel('行情数据覆盖','每个标的展示实际使用的日线来源、条数与截止。');const rows=Object.entries(report.bar_sources||{}).map(([symbol,source])=>{const instrument=(report.instruments||{})[symbol]||{};return [symbol,instrument.name||'—',source.source||'—',source.bar_count??'—',source.earliest_day||'—',source.latest_day||'—']});section.append(table(['标的','名称','日线来源','条数','最早','数据截止'],rows));return section}
function renderAggregate(report){const section=panel('最终投资建议','只读方向汇总：没有自动交易动作，也没有收益率或 Alpha 占位数字。');const list=node('div',undefined,{class:'card-list'});(report.aggregate||[]).forEach(item=>{const card=node('article',undefined,{class:'signal-card'});card.append(node('h3',`${item.symbol}｜${item.direction}`));card.append(node('p',`置信度 ${pct(item.confidence)}｜参与分支：${(item.contributing_branch_ids||[]).join('、')||'无'}｜累计样本：${item.accumulated_samples??0}`));card.append(node('p',item.message||''));list.append(card)});section.append(list);return section}
function renderBranches(report){const section=panel('分支独立结论','每个分支各自保留证据、最大反证和可判定失效条件。未实现分支明确标注且权重为 0。');const groups=new Map();(report.branches||[]).forEach(item=>{const group=groups.get(item.branch_id)||[];group.push(item);groups.set(item.branch_id,group)});for(const [branchId,items] of groups){const card=node('article',undefined,{class:'branch-card'});card.append(node('h3',branchId));const rows=items.map(item=>[item.symbol,item.direction,pct(item.confidence),item.window_used,item.implemented?'已实现':'未实现',item.weight,item.participation_status,item.counter_evidence,item.invalidation]);card.append(table(['标的','方向','置信度','窗口','实现','权重','参与状态','最大反证','失效条件'],rows));section.append(card)}return section}
function renderCoordination(report){const section=panel('内部协调','Stage 2 只对可参与分支等权归一化；贡献度动态权重仍留在 Stage 3。');const facts=node('dl',undefined,{class:'system-facts'});const coordination=report.coordination||{};[['权重模式',report.weight_mode],['累计样本',report.accumulated_samples],['盈利状态',report.profitability_status],['协调规则',coordination.rule],['排除结论数',coordination.excluded_branch_count],['动态权重',coordination.dynamic_contribution_weighting]].forEach(([label,value])=>{const row=node('div');row.append(node('dt',String(label)));row.append(node('dd',String(value??'—')));facts.append(row)});section.append(facts);return section}
function renderReady(report){app.setAttribute('aria-busy','false');app.replaceChildren();const header=node('header',undefined,{class:'topbar'});const brand=node('div',undefined,{class:'brand'});brand.append(node('span','SL',{class:'brand-mark','aria-hidden':'true'}));const title=node('div');title.append(node('strong','Signal Lattice'));title.append(node('span','真实行情 · 独立分支 · 只读研究'));brand.append(title);header.append(brand);header.append(node('span',`数据截止：${report.data_cutoff||'—'}`,{class:'badge'}));app.append(header);const main=node('main',undefined,{id:'main-content',tabindex:'-1'});const hero=node('section',undefined,{class:'panel hero'});const copy=node('div',undefined,{class:'hero-main'});copy.append(node('p','DATA_READY',{class:'eyebrow'}));copy.append(node('h1','真实数据已就绪'));copy.append(node('p',report.message,{class:'lead'}));copy.append(node('p',`报价观察：${time(report.quote_observed_at)}｜自动交易：关闭`,{class:'lead'}));hero.append(copy);main.append(hero,renderSources(report),renderAggregate(report),renderBranches(report),renderCoordination(report));app.append(main);const footer=node('footer','只读研究系统｜数据链路不完整时整页只显示阻断信息｜不自动交易');app.append(footer)}
async function refresh(){try{const response=await fetch('/api/v1/report/latest',{headers:{Accept:'application/json'},cache:'no-store'});const report=await response.json();if(!response.ok||report.state==='SYSTEM_BLOCKED'){renderBlocked();return}if(report.state==='DATA_READY'){renderReady(report);return}renderBlocked()}catch(_error){renderBlocked()}}
refresh();setInterval(refresh,30000);
