"""ABD deterministic acceptance oracles.

Proprietary project code. No order-submission capability is implemented here.
"""

from .canonical_facts import (
    DuplicateKeyError,
    build_evidence,
    evaluate_contract,
    perform_rollback_drill,
    strict_json_load,
    write_phase_evidence,
)
from .authorization import (
    build_evidence as build_authorization_evidence,
    evaluate_contract as evaluate_authorization_contract,
    perform_rollback_drill as perform_authorization_rollback_drill,
    write_phase_evidence as write_authorization_phase_evidence,
)
from .budget import (
    build_evidence as build_budget_evidence,
    evaluate_contract as evaluate_budget_contract,
    perform_rollback_drill as perform_budget_rollback_drill,
    render_scan_report,
    scan_dependency_budget,
    write_phase_evidence as write_budget_phase_evidence,
    write_scan_report,
)
from .external_consent import (
    build_evidence as build_external_consent_evidence,
    evaluate_contract as evaluate_external_consent_contract,
    parse_runbook_contract,
    perform_rollback_drill as perform_external_consent_rollback_drill,
    resolve_consent_event,
    validate_consent_receipt,
    write_phase_evidence as write_external_consent_phase_evidence,
)
from .stage_review import (
    build_evidence as build_stage_review_evidence,
    evaluate_contract as evaluate_stage_review_contract,
    perform_rollback_drill as perform_stage_review_rollback_drill,
    write_stage_review_evidence,
)
from .delivery import verify_stage0_delivery
from .stage1_delivery import verify_stage1_delivery
from .stage1_review import (
    build_evidence as build_stage1_review_evidence,
    evaluate_contract as evaluate_stage1_review_contract,
    perform_rollback_drill as perform_stage1_review_rollback_drill,
    write_stage1_review_evidence,
)
from .customer_press_release import (
    build_evidence as build_customer_press_release_evidence,
    evaluate_contract as evaluate_customer_press_release_contract,
    perform_rollback_drill as perform_customer_press_release_rollback_drill,
    resolve_card_decision,
    write_phase_evidence as write_customer_press_release_phase_evidence,
)
from .customer_faq import (
    build_evidence as build_customer_faq_evidence,
    evaluate_contract as evaluate_customer_faq_contract,
    perform_rollback_drill as perform_customer_faq_rollback_drill,
    resolve_mail_default,
    resolve_recommendation_default,
    resolve_zero_budget_default,
    write_phase_evidence as write_customer_faq_phase_evidence,
)
from .requirements_scope import (
    build_evidence as build_requirements_scope_evidence,
    evaluate_contract as evaluate_requirements_scope_contract,
    perform_rollback_drill as perform_requirements_scope_rollback_drill,
    resolve_stability_default,
    resolve_trace_default,
    write_phase_evidence as write_requirements_scope_phase_evidence,
)
from .metrics_economics import (
    build_evidence as build_metrics_economics_evidence,
    classify_target_evidence,
    evaluate_contract as evaluate_metrics_economics_contract,
    perform_rollback_drill as perform_metrics_economics_rollback_drill,
    resolve_incremental_cost_gate,
    resolve_kill_default,
    resolve_roi_default,
    write_phase_evidence as write_metrics_economics_phase_evidence,
)
from .official_platform_research import (
    build_evidence as build_official_platform_research_evidence,
    evaluate_contract as evaluate_official_platform_research_contract,
    perform_rollback_drill as perform_official_platform_research_rollback_drill,
    resolve_incremental_cost_gate as resolve_official_research_incremental_cost_gate,
    resolve_source_freshness,
    verify_existing_phase_evidence,
    write_phase_evidence as write_official_platform_research_phase_evidence,
)
from .model_risk_research import (
    build_evidence as build_model_risk_research_evidence,
    evaluate_contract as evaluate_model_risk_research_contract,
    perform_rollback_drill as perform_model_risk_research_rollback_drill,
    resolve_claim_admission,
    resolve_stability_contract,
    verify_existing_phase_evidence as verify_model_risk_research_evidence,
    write_phase_evidence as write_model_risk_research_phase_evidence,
)

__all__ = [
    "DuplicateKeyError",
    "build_evidence",
    "evaluate_contract",
    "perform_rollback_drill",
    "strict_json_load",
    "write_phase_evidence",
    "build_authorization_evidence",
    "evaluate_authorization_contract",
    "perform_authorization_rollback_drill",
    "write_authorization_phase_evidence",
    "build_budget_evidence",
    "evaluate_budget_contract",
    "perform_budget_rollback_drill",
    "render_scan_report",
    "scan_dependency_budget",
    "write_budget_phase_evidence",
    "write_scan_report",
    "build_external_consent_evidence",
    "evaluate_external_consent_contract",
    "parse_runbook_contract",
    "perform_external_consent_rollback_drill",
    "resolve_consent_event",
    "validate_consent_receipt",
    "write_external_consent_phase_evidence",
    "build_stage_review_evidence",
    "evaluate_stage_review_contract",
    "perform_stage_review_rollback_drill",
    "write_stage_review_evidence",
    "verify_stage0_delivery",
    "verify_stage1_delivery",
    "build_stage1_review_evidence",
    "evaluate_stage1_review_contract",
    "perform_stage1_review_rollback_drill",
    "write_stage1_review_evidence",
    "build_customer_press_release_evidence",
    "evaluate_customer_press_release_contract",
    "perform_customer_press_release_rollback_drill",
    "resolve_card_decision",
    "write_customer_press_release_phase_evidence",
    "build_customer_faq_evidence",
    "evaluate_customer_faq_contract",
    "perform_customer_faq_rollback_drill",
    "resolve_mail_default",
    "resolve_recommendation_default",
    "resolve_zero_budget_default",
    "write_customer_faq_phase_evidence",
    "build_requirements_scope_evidence",
    "evaluate_requirements_scope_contract",
    "perform_requirements_scope_rollback_drill",
    "resolve_stability_default",
    "resolve_trace_default",
    "write_requirements_scope_phase_evidence",
    "build_metrics_economics_evidence",
    "classify_target_evidence",
    "evaluate_metrics_economics_contract",
    "perform_metrics_economics_rollback_drill",
    "resolve_incremental_cost_gate",
    "resolve_kill_default",
    "resolve_roi_default",
    "write_metrics_economics_phase_evidence",
    "build_official_platform_research_evidence",
    "evaluate_official_platform_research_contract",
    "perform_official_platform_research_rollback_drill",
    "resolve_official_research_incremental_cost_gate",
    "resolve_source_freshness",
    "verify_existing_phase_evidence",
    "write_official_platform_research_phase_evidence",
    "build_model_risk_research_evidence",
    "evaluate_model_risk_research_contract",
    "perform_model_risk_research_rollback_drill",
    "resolve_claim_admission",
    "resolve_stability_contract",
    "verify_model_risk_research_evidence",
    "write_model_risk_research_phase_evidence",
]
