#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""ADP-S7-P02-T080 -- generate a Node behavioural test of the REAL grade()/gradeUndo()/gradeCommit() client
code extracted verbatim from the worker, with stubbed DOM / fetch / timers, to prove the undo semantics:

  * clicking a grade gives SYNCHRONOUS feedback (picked class + undo control) and fires NO write;
  * clicking undo during the window fires NO write ever (honours 不得改写既有生产数据);
  * letting the window elapse fires EXACTLY ONE /api/grade write (the deferred commit).

The client JS is lifted verbatim from the worker (the only server interpolation, ${jsStr(sel.item_id)}, is
replaced with a literal id) so the test exercises the shipped code, not a re-implementation."""
import pathlib
import re

V01 = pathlib.Path("/Users/linzezhang/Documents/Codex/main_worktree/CodexProject/adp/"
                   "arxiv-daily-push/docs/pursuing_goal/v0_1")
OUT = V01 / "evidence" / "ADP-S7-P02-T080" / "test-results" / "undo_behavior_test.js"
src = (V01.parents[3] / "arxiv-daily-push/deploy/cloudflare/worker_cloud.js").read_text(encoding="utf-8")

# extract the studyPage grade client script verbatim (var _grading=false,_pend=null; ... up to </script>)
i = src.index("var _grading=false,_pend=null;")
j = src.index("</script>", i)
client = src[i:j]
# substitute the one server interpolation with a literal id (keeps the real logic intact)
client = client.replace("${jsStr(sel.item_id)}", "'test-item'")
assert "${" not in client, "unsubstituted server interpolation remains: " + client[client.find('${'):client.find('${')+40]

harness = r"""// AUTO-GENERATED by build_undo_behavior_test.py -- exercises the REAL extracted grade client code.
'use strict';
let fetchCalls = [];
global.fetch = async (url, opts) => { fetchCalls.push({url, opts}); return { ok: true, json: async () => ({due_at:'2026-07-20', interval:3, evidence_state:'ok'}) }; };
// controllable timers: capture the interval callback so the test drives the clock
let intervalCb = null, intervalCleared = false;
global.setInterval = (cb) => { intervalCb = cb; intervalCleared = false; return 1; };
global.clearInterval = () => { intervalCleared = true; intervalCb = null; };

// minimal DOM stub
function mkEl(){ return { className:'', _cls:new Set(), classList:{add(c){this._add(c);}, remove(c){this._rm(c);}}, disabled:false, _attrs:{},
  textContent:'', innerHTML:'', style:{}, setAttribute(k,v){this._attrs[k]=v;}, removeAttribute(k){delete this._attrs[k];}, getAttribute(k){return this._attrs[k];} }; }
function wireCls(el){ el.classList.add=(c)=>el._cls.add(c); el.classList.remove=(c)=>el._cls.delete(c); el.classList.contains=(c)=>el._cls.has(c); }
let gradeButtons = [mkEl(), mkEl(), mkEl(), mkEl()];
gradeButtons.forEach((b,i)=>{ wireCls(b); b.textContent=['忘了','困难','良好','轻松'][i]; });
let rEl = mkEl(); wireCls(rEl);
global.document = {
  querySelectorAll: (sel) => { const a = gradeButtons.slice(); a.forEach=Array.prototype.forEach.bind(a); return a; },
  getElementById: (id) => id==='r' ? rEl : null,
};

// ---- the REAL extracted client code ----
%CLIENT%
// ---------------------------------------

const assert = (c,m)=>{ if(!c){ console.log('FAIL:', m); process.exitCode=1; } else console.log('ok:', m); };

// scenario 1: click a grade -> synchronous feedback, NO write yet
grade(3, gradeButtons[2]);
assert(gradeButtons[2]._cls.has('picked'), 'click marks the chosen grade as picked (synchronous feedback)');
assert(gradeButtons.every(b=>b.disabled===true), 'all grade buttons disabled on click (synchronous)');
assert(/撤销/.test(rEl.innerHTML) && /undo/.test(rEl.innerHTML), 'an undo control is rendered synchronously');
assert(fetchCalls.length===0, 'NO write is fired on click (write is deferred behind the undo window)');

// scenario 2: click undo during the window -> NO write ever, reverted
gradeUndo();
assert(intervalCleared===true, 'undo cancels the pending countdown timer');
assert(fetchCalls.length===0, 'undo fires NO write (honours 不得改写既有生产数据)');
assert(gradeButtons.every(b=>b.disabled===false), 'undo re-enables the grade buttons');
assert(rEl.getAttribute('data-state')==='' , 'undo clears the state marker');

// scenario 3: click again and let the window elapse -> EXACTLY ONE write (deferred commit)
grade(4, gradeButtons[3]);
assert(fetchCalls.length===0, 'still no write immediately after the second click');
// drive the clock: the countdown starts at 4 and commits when it reaches 0
for (let t=0; t<5 && intervalCb; t++) intervalCb();
// gradeCommit is async; flush microtasks
setTimeout(()=>{
  assert(fetchCalls.length===1, 'exactly one /api/grade write after the window elapses');
  assert(fetchCalls.length===1 && /\/api\/grade\/test-item\/4/.test(fetchCalls[0].url), 'the deferred write targets the chosen grade');
  console.log(process.exitCode?('\nRESULT = FAIL'):('\nRESULT = PASS'));
}, 0);
"""
OUT.write_text(harness.replace("%CLIENT%", client), encoding="utf-8")
print("wrote", OUT, f"({len(client)} bytes of extracted client code)")
