from __future__ import annotations


GROUP_CODE_TO_TEAM = {
    "ARG": "Argentina",
    "ALG": "Algeria",
    "AUS": "Australia",
    "AUT": "Austria",
    "BEL": "Belgium",
    "BIH": "Bosnia-Herzegovina",
    "BRA": "Brazil",
    "CAN": "Canada",
    "CIV": "Cote d Ivoire",
    "COD": "DR Congo",
    "COL": "Colombia",
    "CPV": "Cabo Verde",
    "CRO": "Croatia",
    "CUW": "Curacao",
    "CZE": "Czechia",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "ENG": "England",
    "ESP": "Spain",
    "FRA": "France",
    "GER": "Germany",
    "GHA": "Ghana",
    "HAI": "Haiti",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "JOR": "Jordan",
    "JPN": "Japan",
    "KOR": "South Korea",
    "KSA": "Saudi Arabia",
    "MAR": "Morocco",
    "MEX": "Mexico",
    "NED": "Netherlands",
    "NOR": "Norway",
    "NZL": "New Zealand",
    "PAN": "Panama",
    "PAR": "Paraguay",
    "POR": "Portugal",
    "QAT": "Qatar",
    "RSA": "South Africa",
    "SCO": "Scotland",
    "SEN": "Senegal",
    "SUI": "Switzerland",
    "SWE": "Sweden",
    "TUN": "Tunisia",
    "TUR": "Turkiye",
    "URU": "Uruguay",
    "USA": "USA",
    "UZB": "Uzbekistan",
}

EXPECTED_TEAMS = [
    "Mexico",
    "Czechia",
    "South Korea",
    "South Africa",
    "Switzerland",
    "Bosnia-Herzegovina",
    "Canada",
    "Qatar",
    "Brazil",
    "Morocco",
    "Scotland",
    "Haiti",
    "USA",
    "Turkiye",
    "Paraguay",
    "Australia",
    "Germany",
    "Ecuador",
    "Cote d Ivoire",
    "Curacao",
    "Netherlands",
    "Japan",
    "Sweden",
    "Tunisia",
    "Belgium",
    "Egypt",
    "Iran",
    "New Zealand",
    "Spain",
    "Uruguay",
    "Saudi Arabia",
    "Cabo Verde",
    "France",
    "Norway",
    "Senegal",
    "Iraq",
    "Argentina",
    "Austria",
    "Algeria",
    "Jordan",
    "Portugal",
    "Colombia",
    "Uzbekistan",
    "DR Congo",
    "England",
    "Croatia",
    "Ghana",
    "Panama",
]
EXPECTED_TEAM_SET = set(EXPECTED_TEAMS)


def normalize_world_cup_team_name(team: str) -> str:
    aliases = {
        "Bosnia Herzegovina": "Bosnia-Herzegovina",
        "Bosn-Herzegovina": "Bosnia-Herzegovina",
        "Congo DR": "DR Congo",
        "Korea Republic": "South Korea",
    }
    return aliases.get(team, team)
