import test from "node:test";
import assert from "node:assert/strict";
import { collectNotebookSummaries, collectSnapshot } from "../src/core/collector.js";
import { EXPORT_PROFILES, USER_REGION_END, USER_REGION_START } from "../src/core/constants.js";
import { createDemoCaller } from "../src/core/demo.js";
import { buildExport } from "../src/core/exporter.js";
import { createDeterministicZip, crc32, readZipEntries } from "../src/core/zip.js";
import { decodeUtf8, sha256Hex, stableStringify, utf8 } from "../src/core/util.js";
import { bytesEqual } from "./helpers.mjs";

async function demoSnapshot(profile = EXPORT_PROFILES.PORTABLE) {
  const call = createDemoCaller();
  const summaries = await collectNotebookSummaries({ key: "demo-only", call });
  return collectSnapshot({ key: "demo-only", summaries, exportProfile: profile, call, includeReadingStatistics: true });
}

function inventory(snapshot) { return snapshot.books.map(book => book.source.bookId); }

async function rebuildWithConsistentChecksums(entries, manifest) {
  const updated = new Map(entries);
  updated.set("manifest.json", utf8(stableStringify(manifest)));
  const lines = [];
  for (const path of [...updated.keys()].filter(path => path !== "CHECKSUMS.sha256").sort()) lines.push(`${await sha256Hex(updated.get(path))}  ${path}`);
  updated.set("CHECKSUMS.sha256", utf8(`${lines.join("\n")}\n`));
  return createDeterministicZip(Array.from(updated, ([path, data]) => ({ path, data })));
}

test("deterministic export produces identical bytes and complete evidence files", async () => {
  const snapshot = await demoSnapshot();
  const options = { profile: EXPORT_PROFILES.PORTABLE, includeOfflineSearch: true, knownSourceBookIds: inventory(snapshot), sourceInventoryComplete: true };
  const first = await buildExport(snapshot, options);
  const second = await buildExport(snapshot, options);
  assert.ok(bytesEqual(first.bytes, second.bytes));
  const entries = await readZipEntries(first.bytes);
  for (const path of ["manifest.json", "README.md", "BOOKS_INDEX.md", "EXPORT_REPORT.md", "data/canonical-reading-model.json", "offline/index.html", "chatgpt/阅读笔记上下文.md", "CHATGPT_使用说明.md", "CHECKSUMS.sha256"]) assert.ok(entries.has(path), path);
  const manifest = JSON.parse(decodeUtf8(entries.get("manifest.json")));
  assert.equal(manifest.status, "COMPLETE");
  assert.equal(manifest.bookCount, 2);
  assert.equal(manifest.updatedBookCount, 2);
  assert.equal(manifest.retainedBookCount, 0);
  assert.equal(manifest.tombstoneCount, 0);
  assert.equal(manifest.chatgptHandoff.transport, "manual-user-confirmed-upload");
  assert.equal(manifest.chatgptHandoff.contextPath, "chatgpt/阅读笔记上下文.md");
  assert.ok(manifest.books.every(record => /^[0-9a-f]{64}$/.test(record.generatedSha256)));
  assert.equal(manifest.files.length, entries.size - 2); // excludes manifest and self-referential checksum file
});

test("previous export permits only protected-region edits and preserves them byte-for-byte", async () => {
  const snapshot = await demoSnapshot();
  const options = { profile: EXPORT_PROFILES.PORTABLE, knownSourceBookIds: inventory(snapshot), sourceInventoryComplete: true };
  const first = await buildExport(snapshot, options);
  const entries = await readZipEntries(first.bytes);
  const manifest = JSON.parse(decodeUtf8(entries.get("manifest.json")));
  const bookPath = manifest.books[0].path;
  const original = decodeUtf8(entries.get(bookPath));
  const custom = "\n\n我的永久判断：保留这段。\n- 待办是用户自己的文字，不是开发占位。\n\n";
  const start = original.indexOf(USER_REGION_START) + USER_REGION_START.length;
  const end = original.indexOf(USER_REGION_END);
  const edited = `${original.slice(0, start)}${custom}${original.slice(end)}`;
  // User edits commonly leave manifest/checksum metadata unchanged. This is allowed
  // only because the generated bytes outside the protected region still match.
  const previousZip = createDeterministicZip(Array.from(entries, ([path, data]) => ({ path, data: path === bookPath ? edited : data })));
  const next = await buildExport(snapshot, { ...options, previousZip });
  const nextEntries = await readZipEntries(next.bytes);
  const nextText = decodeUtf8(nextEntries.get(bookPath));
  assert.ok(nextText.includes(custom));
});

test("coordinated checksum edits cannot authorize changes outside the protected region", async () => {
  const snapshot = await demoSnapshot();
  const options = { profile: EXPORT_PROFILES.PORTABLE, knownSourceBookIds: inventory(snapshot), sourceInventoryComplete: true };
  const first = await buildExport(snapshot, options);
  const entries = await readZipEntries(first.bytes);
  const manifest = JSON.parse(decodeUtf8(entries.get("manifest.json")));
  const bookRecord = manifest.books[0];
  const original = decodeUtf8(entries.get(bookRecord.path));
  const tampered = original.replace("## 导出说明", "## 被修改的生成内容");
  assert.notEqual(tampered, original);
  entries.set(bookRecord.path, utf8(tampered));
  const actualHash = await sha256Hex(entries.get(bookRecord.path));
  bookRecord.sha256 = actualHash;
  const fileRecord = manifest.files.find(record => record.path === bookRecord.path);
  fileRecord.sha256 = actualHash;
  fileRecord.bytes = entries.get(bookRecord.path).byteLength;
  const previousZip = await rebuildWithConsistentChecksums(entries, manifest);
  await assert.rejects(() => buildExport(snapshot, { ...options, previousZip }), error => error.code === "PREVIOUS_EXPORT" && /个人补充区之外/.test(error.message));
});

test("selection retention and upstream tombstones are explicit and non-destructive", async () => {
  const full = await demoSnapshot();
  const fullIds = inventory(full);
  const first = await buildExport(full, { profile: EXPORT_PROFILES.PORTABLE, knownSourceBookIds: fullIds, sourceInventoryComplete: true });
  const reduced = { ...full, books: [full.books[0]] };

  // The second book still exists upstream but was not selected: retain its last
  // verified snapshot rather than silently deleting it.
  const selectedOnly = await buildExport(reduced, { profile: EXPORT_PROFILES.PORTABLE, previousZip: first.bytes, knownSourceBookIds: fullIds, sourceInventoryComplete: true });
  assert.equal(selectedOnly.manifest.bookCount, 2);
  assert.equal(selectedOnly.manifest.retainedBookCount, 1);
  assert.equal(selectedOnly.manifest.tombstoneCount, 0);

  // The second book is absent from a complete inventory: archive its old Markdown
  // as a tombstone and keep that state stable on the next export.
  const remainingIds = [reduced.books[0].source.bookId];
  const deleted = await buildExport(reduced, { profile: EXPORT_PROFILES.PORTABLE, previousZip: first.bytes, knownSourceBookIds: remainingIds, sourceInventoryComplete: true });
  assert.equal(deleted.manifest.bookCount, 1);
  assert.equal(deleted.manifest.tombstoneCount, 1);
  const deletedEntries = await readZipEntries(deleted.bytes);
  assert.ok(deletedEntries.has("DELETED_UPSTREAM.md"));
  assert.ok(deletedEntries.has(deleted.manifest.tombstones[0].path));
  const repeated = await buildExport(reduced, { profile: EXPORT_PROFILES.PORTABLE, previousZip: deleted.bytes, knownSourceBookIds: remainingIds, sourceInventoryComplete: true });
  assert.ok(bytesEqual(deleted.bytes, repeated.bytes));
});

test("ZIP rejects traversal, duplicate paths and raw tampering", async () => {
  assert.equal(crc32(utf8("123456789")), 0xcbf43926);
  assert.throws(() => createDeterministicZip([{ path: "../escape", data: "x" }]), error => error.code === "UNSAFE_PATH");
  assert.throws(() => createDeterministicZip([{ path: "a.txt", data: "x" }, { path: "a.txt", data: "y" }]), error => error.code === "ARCHIVE");
  const zip = createDeterministicZip([{ path: "a.txt", data: "hello" }]);
  const tampered = zip.slice();
  tampered[35] ^= 0xff;
  await assert.rejects(() => readZipEntries(tampered), error => error.code === "ARCHIVE");
});
